# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            stefan.grotz.me
tagline:          'test'
description:      'test'
url:              http://stefangrotz.github.io
baseurl:          /

author:
  name:           'test'
  url:            http://test

paginate:         5

# Custom vars
version:          1.2.3

github:
  repo:           https://github.com/poole/hyde

# Gems
gems:
  - jekyll-gist